//Rest Client requests for handling user data *(Rest Client Plugin can be used) 
POST http://localhost:9000/userHandler/register
Content-Type: application/json

{
    "username":"vinay",
    "password":"vinay123",
    "emailId":"vinay21@gmail.com"
}

###
GET http://localhost:9000/userHandler/listUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjM5MWRkYWNhOTdkNTJmMDQzZDFmMzciLCJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmEkMTAkeWRTeEZ3OTNDMmhYcWVkZ0VWZmJHLmM2dm9KWWswRDNkNENOVlUwL0lkUXhocng0NENEa3EiLCJpYXQiOjE1OTc2NDIzNDB9.rsdQJIuq57HvlWDKQXcmxGeiX1YDHnec9MlSaTPo5Ek
###
PUT  http://localhost:9000/userHandler/updateUsers
Content-Type: application/json

{
    "username":"ashish",
    "password":"ashish1533",
    "emailId":"ashishchandwani928@gmail.com"
}

###
POST http://localhost:9000/userHandler/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

